# Generated by Django 5.0.4 on 2024-04-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_alter_reserva_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='size_del_grupo',
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='grupos.size'),
            preserve_default=False,
        ),
    ]
