# Generated by Django 5.0.4 on 2024-04-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_remove_clase_size_del_grupo_clase_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='grupos.grupo'),
        ),
    ]
