# Generated by Django 5.0.4 on 2024-04-15 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_alter_clase_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
